### ISSUE TITLE
Configuration Error

### ISSUE THREAD

**Issue by JBa-5176** [xilense/aimp_custom_component#2]
Hi,
I have a probleme with the installation

with Configuration.yaml

==>
_Configuration non valide !
Erreurs de configuration
Error loading /config/configuration.yaml: Secret aimp_ip not defined_

Why ??

Thanks

**Comment by SefWR-0** [comment]
in which format to specify IP

**Comment by xilense** [comment]
replace **host** config or _aimp_ip_ value with your pc network ip
you can check your ip on your router

_config example:_
```
media_player:
  - platform: aimp
    name: 'AIMP'
    host: 192.168.0.11
    port: 3333
```
